src/components/common/Tabs/ViewTabs.jsx
<br>
ViewTabs의 마크업 구조를 변경하고 props를 수정하였다.
<br><br>
- prettier 미적용된 부분 적용
- 그리드형/리스트형 구조 -> 리스트형/그리드형 구조로 마크업 변경
- 선택된 탭에 따라 활성화 되게끔 onClick props 추가
<br><br>
- ViewTabs 컴포넌트 사용방법
```jsx
<ViewTabs selectedTab={selectedTab} onClick={} />
```
<br><br>
- Close #40
<br><br>
=> ♻️ refactor: ViewTabs 마크업 구조 변경 및 props 수정

src/components/common/BottomSheet/BasicModal.jsx, src/components/common/BottomSheet/BottomSheet.jsx, src/components/common/BottomSheet/BottomSheetStyle.jsx, src/components/common/BottomSheet/ListModal.jsx, src/components/common/Modal/Modal.jsx
기본 BottomSheet틀을 만들고, 경우에 따라 BasicModal, ListModal을 받아오도록 하였다.
<br>
공통 Modal UI 컴포넌트 구현
<br><br>
기본 BottomSheet파일을 만들고 상황에 따라 BasicModal 또는 ListModal을 불러오게 했다.
기본 BottomSheet의 경우, 바깥의 버튼을 누르면 ModalBox가 올라오도록 하고, Dim 부분 혹은 모달의 헤더(HeaderModal)을 누르면 내려가도록 구현했다.
ListModal의 경우, 리스트를 받아올 때 총 height가 425px이 넘어가면 스크롤으로 리스트를 보여지게 구현하였다(스크롤은 보이지 않게 숨겼음)
<br><br>
`const [isShow, setIsShow] = useState(false);
const handleClickButton = () => {
setIsShow(true);
};
return (
<>
<BottomSheet type='' isShow={isShow} setIsShow={setIsShow}></BottomSheet>
</>
);`
<br><br>
- Close #19 
<br><br>
=> 🎨 style: 공통 Modal UI 컴포넌트 구현

src/components/common/BottomSheet/BasicModal.jsx, src/components/common/BottomSheet/BottomSheet.jsx, src/components/common/BottomSheet/BottomSheetStyle.jsx, src/components/common/BottomSheet/ListModal.jsx, src/layout/BasicLayout.jsx
<br>
BottomSheet 컴포넌트 코드를 최소화 하기 위한 리팩토링을 진행했다.
<br><br>
- props에 전달한 click 함수로 modal handler와 dim으로도 모달을 닫을 수 있게 했다.
- BottomSheet가 가지고 있는 animation에 대한 상태값을 제거했다.
- props에 따른 animation 동작 코드 중복 줄였다.
- BottomSheet의 height를 auto로 두어 BottomSheet의 Slide 애니메이션의 높이와 BottomSheet의 height를 조절하기 위한 LEN props를 삭제했다.
- BottomSheet의 Handler의 위치를 콘텐츠로 받아올 children의 하단으로 마크업 위치를 옮겼다. (접근성 측면)
- BottomSheet의 ListModal과 BasicMdoal에 렌더링 될 props와 onClick을 전달하기 위해 BottomSheet와 분리했다.
- ListModal, BasicModal 디자인을 피그마와 맞췄다.
- BasicModal의 경우 최대 높이를 지정하고, 지정한 높이를 넘어가면 스크롤이 되게 스타일을 수정하였다.
- BottomSheet 뒤에 스크롤 기능을 막았다.
<br><br>
- page 컴포넌트에서 BottomSheet 사용 방법
1. BottomSheet 안에 LIstModal을 렌더링할 경우
```jsx
export default function HomePage() {
const [isShow, setIsShow] = useState(false);
const handleClickModalOpen = …
```
=> ♻️ refactor: BottomSheet 컴포넌트 코드 최소화 리팩토링

src/components/common/Carousel/CarouselStyle.jsx, src/components/common/Tabs/SpaceTabs.jsx, src/pages/HomePage/HomePage.jsx
<br>
홈페이지 마크업 및 스와이프, 필터링 기능을 구현했다.
<br><br>
- 높은 좋아요 순으로 mock data를 받아와 상위 Carousel에 보여줬다.
- 게시글이 없다면 게시글이 없다는 화면을, 게시글이 있다면 카드 리스트 형태로 보여줬다.
- SpaceTabs가 옆으로 터치스크롤이 되게 했다.(스와이프)
- Mock 데이터를 받아와 탭에 따른 posts 데이터를 보여줬다.
- 아래로 스크롤했을 때 SpaceTabs가 맨 위에 붙게 했다.
<br><br>
- 탭 버튼을 클릭하여 데이터를 받아올 때 좌우 스크롤이 맨 앞으로 오는 버그 수정
- 버튼을 클릭한 상태로 스와이프시 버튼 클릭이 되는 버그 수정(스와이프와 클릭 이벤트 구분)
-  `position: sticky`를 사용하여 아래로 스크롤 시 tab이 맨 위에 붙음
<br><br>
- Close #54
<br><br>
=> ✨ feat: 홈페이지 마크업 및 기능 구현

src/components/LoginSignUp/Login/Login.jsx, src/components/LoginSignUp/Main/Main.jsx, src/components/LoginSignUp/SignUp/SignUp.jsx, src/pages/LoginPage/LoginPage.jsx, src/pages/MainPage/MainPage.jsx, src/pages/SignupPage/SignupPage.jsx
Link 컴포넌트를 사용하여 페이지 내에서의 전환과 이동을 구현하는 것이 적절하다고 판단하여 a태그를 Link컴포넌트로 대체하였다. 또한 필요없는 함수 및 코드들을 삭제하였다.
<br>
a 태그를 Link 컴포넌트로 대체하여 href 오류를 해결하였고, 불필요한 함수 및 코드를 삭제하였다.
<br><br>
새로 고침되어 다른 페이지로 이동하는 a태그보다는 Link 컴포넌트를 사용하여 페이지 내에서의 전환과 이동을 구현하는 것이 적절하다고 판단하여 변경하였다. 기존에 a 태그 내에 props로 전달해준 함수와 관련된 코드들은 삭제하였다.
<br><br>
<br><br>
- Close #72 
<br><br>
=> 🐛 fix: a 태그를 Link 컴포넌트로 대체하여 href 오류 해결 (#72)

src/components/LoginSignUp/SetUserProfile/SetUserProfile.jsx, src/components/LoginSignUp/SetUserProfile/SetUserProfileForm.jsx, src/components/LoginSignUp/SetUserProfile/SetUserProfileFormStyle.jsx, src/components/LoginSignUp/SetUserProfile/SetUserProfileStyle.jsx, src/components/common/ProfileImageUpload/ProfileImageUpload.jsx, src/components/common/ProfileImageUpload/ProfileImageUploadStyle.jsx
<br>
SetUserProfile 컴포넌트를 SetUserProfileForm 과 분리
<br><br>
- SetUserProfile에서 사용되는 상태값과 handler 이벤트를 SetUserProfileForm으로 분리했다.
- __InValid 초기값 세팅을 false -> true로 변경하여 로직의 오류를 수정했다.
- 필요없는 코드 줄을 삭제했다.
- SetUserProfilForm에 기본값으로 유저 데이터를 사용할 수 있게 props를 추가했다.
<br><br>
- 회원가입 페이지에서 사용 방법
```jsx
// 다음 단계로 넘어가기 위한 버튼을 활성화 해줄 setState 함수를 전달
<SetUserProfileForm setIsButtonActive={setIsButtonActive} />
```
- 프로필 수정 페이지에서 사용 방법
```jsx
// 현재 로그인된 사용자의 정보를 userData props에 넘겨주어 수정 페이지에서 input의 기본 값으로 사용
<SetUserProfileForm userData={profileData.profile} setIsButtonActive={setIsButtonActive} />
```
추후 Form 컴포넌트에서의 상태값을 객체로 합쳐주어 API 요청에 사용할 수 있게끔 작업을 진행해야한다.
<br><br>
- Close #78 
<br><br>
=> ♻️ refactor: SetUserProfile 컴포넌트 폼 입력 부분 분리

src/api/profileApi.js, src/components/LoginSignUp/SetUserProfile/SetUserProfileForm.jsx, src/components/Profile/ProfileCard/ProfileCard.jsx, src/components/common/Header/Header.jsx, src/components/common/ProfileImageUpload/ProfileImageUpload.jsx, src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx, src/pages/ProfilePage/ProfilePage/ProfilePage.jsx, src/pages/ProfilePage/UserProfilePage/UserProfilePage.jsx, src/pages/Router.jsx
<br>
프로필 수정 페이지를 마크업하고 API를 연동하여 수정 기능을 구현했다.
<br><br>
- MyProfilePage와 UserProfilePage를 ProfilePage로 통합하였다.
- url의 params에 따라 내 정보 데이터 패칭/유저 정보 데이터 패칭을 분리하여 실행했다.
- 프로필 수정 버튼을 눌렀을 때 현재 내 프로필 정보를 넘겨주어 프로필 수정 페이지에 기존 프로필 정보가 보이게 했다.
- 프로필 수정이 완료되면 프로필 페이지로 이동하게 했다.
<br><br>
- 회원가입 프로필 설정에서 SetUserProfileForm을 사용할 때는 아래와 같이 사용하면 됩니다!
```jsx
const [isButtonActive, setIsButtonActive] = useState(false);
const [profile, setProfile] = useState({
username: '',
accountname: '',
intro: '',
image: '',
});
return(
// ....
<SetUserProfileForm
setIsButtonActive={setIsButtonActive}
setData={setProfile}
/>
)
```
<br><br>
- Close #71 
<br><br>
=> ✨ feat: 프로필 수정 페이지 마크업 및 API 연동하여 수정 기능 구현

src/components/PostUpload/ModalProductList/ModalProductList.jsx, src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
<br>
게시글 업로드와 수정에서 이미지 변경 취소 시 오류와 게시글 등록 시 태그할 상품목록이 1개 남아있음에도 목록에 뜨지 않는 문제를 해결했다.
<br><br>
- 태그할 수 있는 상품목록이 보이는 조건의 비교문을 잘못 작성하여 발생한 문제로, 해결했다.
- 새로운 파일이 들어와야 이미지를 변경하도록 file이 있을때 함수를 실행하도록 if문 안으로 넣어 문제를 해결했다. 
<br><br>
<br><br>
- Close #92 
<br><br>
=> 🐛 fix: 게시글 업로드 시 이미지 변경 취소 오류와 상품목록 조건의 오류 발생

src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
<br>
프로필 수정 시 이미지 변경 후, 다시 업로드 버튼을 누르고 취소할 경우 발생하는 오류를 해결했다.
<br><br>
- imgRef 즉, `input type=file` 에서 선택된 이미지가 없다면 File API가 실행되지 않고, 선택된 이미지가 있다면 File API가 실행되게 함으로써 에러를 해결하였다.
<br><br>
이미지 선택 시 이미지 크기가 특정 값을 넘어가면 업로드 오류가 발생한다.
<br><br>
- Close #89 
<br><br>
=> 🐛 fix: 프로필 수정 시 이미지 변경 후, 다시 업로드 버튼을 누르고 취소할 경우 발생하는 오류 해결

src/api/postApi.js, src/api/productApi.js, src/api/profileApi.js, src/components/Profile/PostList/PostList.jsx, src/components/Profile/ProductDetailCard/ProductDetailCard.jsx, src/components/Profile/ProfileCard/ProfileCard.jsx, src/components/common/Card/PostCard/PostCard.jsx, src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx, src/pages/ProductPage/ProductEditPage/ProductEditPage.jsx, src/pages/ProductPage/ProductPage.jsx, src/pages/ProductPage/ProductUploadPage/ProductUploadPage.jsx, src/pages/ProfilePage/ProfilePage/ProfilePage.jsx, src/pages/Router.jsx, src/utils/filterPosts.js
<br>
ProfilePage에서 사용자에 따라 보여지는 모달창을 구분하고, Confirm 컴포넌트와 연결해 기능을 구현했다.
<br><br>
- 프로필 더보기를 눌렀을 경우 [프로필 설정 페이지로 이동 / 로그아웃]이 되게 했다.
- 상품 더보기를 눌렀을 경우 사용자에 따라 [웹사이트보기 / 웹사이트보기 | 삭제 | 수정] 버튼이 보여지게 했다.
- 상품 더보기를 눌렀을 경우 보여지는 버튼에 따른 동작을 구현했다.
- 게시글 더보기를 눌렀을 경우 사용자에 따라 [신고하기 / 삭제 | 수정]이 보여지고, 해당 기능들을 react-query와 연결하여 구현했다.
- url에 내 프로필 accoutname을 파라미터로 포함하고 있어도 유저 프로필이 아닌 내 프로필로 인식하게 했다.
<br><br>
- 현재 프로필 페이지에서 보여지는 게시글의 개수는 기본 10개이다. 추후 무한 스크롤링을 하거나 제한을 해둘지 고민해볼 것
<br><br>
- Close #90 
<br><br>
=> ✨ feat: ProfilePage 사용자에 따른 모달창 구분 및 Confirm 연결

src/components/Profile/PostList/PostList.jsx, src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
<br>
PostList 컴포넌트 재사용성을 위해 props 값을 수정했다.
<br><br>
PostList에 있는 UserSimpleInfo에 사용되는 현재 프로필 데이터가 필요하다 생각하여 ProfilePage에서 PostList로 props로 프로필 정보를 전달해주었다. 이를 PostList에 있는 게시물 데이터에서 작성자 정보를 전달할 수 있으므로 PostList에 props를 전달해주지 않아도 컴포넌트 내에서 해결할 수 있었다.
<br><br>
<br><br>
- Close #100 
<br><br>
=> ♻️ refactor: PostList 컴포넌트 재사용성을 위해 props 값 수정

src/pages/PostPage/PostPage/PostPage.jsx
<br>
프로필 정보 불러오기 변수명을 수정하여 오류를 해결했다.
<br><br>
api호출 함수내에서 리턴값이 data.user로 변경되었는데 확인하지 못해 setMyProfile의 인자로 data.user를 넣어 발생한 문제로 데이터로 넣는 값을 data로 변경하여 문제를 해결했다.
<br><br>
<br><br>
- Close #105 
<br><br>
=> 🐛 fix: 게시글 상세 페이지의 myprofile을 찾지 못하는 문제 해결

src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
<br>
프로필 수정 페이지에서 계정 ID 수정 시 프로필 페이지로 이동했을 때 이전 데이터를 요청하는 오류를 해결했다.
<br><br>
- react query에서 onMutate 메서드를 사용하여 mutate 되기 전에 이전 캐시 값을 제거했다.
<br><br>
- Close #121 
<br><br>
=> 🐛 fix: 프로필 수정 시 프로필 페이지에서 이전 데이터를 요청하는 오류 해결

src/api/searchApi.js, src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx, src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx, src/hooks/useDebounce.js, src/pages/SearchPage/SearchPage.jsx
<br>
검색 API 연동 및 추가 기능을 구현했다.
<br><br>
<br><br>
- 아무것도 검색 안했을 때 최근 검색했던 프로필 목록을 보여준다.
- 검색했을 때 일치하는 단어에 하이라이트를 해준다.
<br><br>
- Close #117
<br><br>
=> ✨ feat: 검색 API 연동 및 추가 기능 구현

src/pages/SearchPage/SearchPage.jsx
<br>
검색 결과 목록이 7개 이하일 때도 더보기 버튼이 보이던 것을 안보이게 수정했다.
<br><br>
useQuery의 select 안에서 slice까지 모두 처리해서 전체 검색 목록의 수를 불러오지 못해서 slice를 밖으로 빼 전체 검색 목록의 개수가 7개 이하일 때 더보기 버튼을 안보이게 하는 로직을 추가하였다.
<br><br>
- 7개 이하일 때 
- 7개 초과일 때
<br><br>
- Close #132
<br><br>
=> 🐛 fix: 검색 결과 목록이 7개 이하일 때 더보기 버튼 안보이게 수정

src/api/axiosInstance.js, src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
<br>
로그아웃 후 재 로그인 시 기존 데이터가 보이는 오류를 해결했다.
<br><br>
axios 인스턴스에 Authorization의 값이 고정되어 다시 재 로그인을 했을 때 기존 데이터가 보이는 현상이 발생했다.
따라서 axios의 interceptors를 사용해서 axios 요청 전에 Authorization을 세팅할 수 있게 했다.
<br><br>
[Axios Docs](https://axios-http.com/docs/interceptors)
<br><br>
- Close #140 
<br><br>
=> 🐛 fix: 로그아웃 후 재 로그인 시 기존 데이터가 보이는 오류 해결

src/api/profileApi.js, src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
<br>
프로필 수정에서 이미 가입된 ID를 입력할 경우, api에서 데이터를 불러와서 에러메시지를 SetUserProfileForm에 전달하였다.
<br><br>
- ProfileApi.js의 updateProfile에서 api 불러오는 부분 수정
- onError 부분의 메시지를 ProfileForm에 전달
<br><br>
- error콘솔 출력 내용, 따라서 error.response.data.message를 SetUserProfileForm에 메시지로 전달해줘야함
- feature/#137에서 올릴 작업내용이 남아있어서 브랜치 삭제는 추후에 진행
<br><br>
- Close #146 
<br><br>
=> ✨ feat: 프로필 수정에서 이미 가입된 ID를 입력할 경우 경고메시지를 출력하는 기능 구현

src/pages/FeedPage/FeedPage.jsx, src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx, src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
<br>
피드, 팔로워, 팔로잉 페이지에서 스크롤 시 추가 데이터를 받아오지 않는 오류가 발생했다.
<br><br>
- observer가 타겟팅한 대상에 높이값을 지정한다.
- 팔로워, 팔로잉 페이지의 Spinner 위치 조절
- 팔로워, 팔로잉 페이지의 경우 isLoading일 때 Spinner 컴포넌트가 동작하게 되는데, Spinner 컴포넌트의 높이가 100vh이기 때문에 로딩중일 때 observer는 타겟팅 대상을 잃어버린다. 
- 따라서 Spinner의 위치를 타겟팅 대상 안에 넣어준다.
<br><br>
- Close #176 
<br><br>
=> 🐛 fix: 피드, 팔로워, 팔로잉 페이지 무한 스크롤 기능 오류 해결

src/components/PostUpload/PostProductTag/PostProductTag.jsx, src/components/PostUpload/PostProductTag/PostProductTagStyle.jsx, src/components/PostUpload/ProductBubble/ProductBubble.jsx, src/constants/common.js, src/hooks/useBubbleLocation.js
<br>
게시글 등록 시 +버튼을 클릭뿐아니라 드래그해도 상품 태그 가능하도록 수정했다.
<br><br>
- 위치 연산을 위한 숫자의 경우 상수로 관리
- 태그말풍선 위치 계산 로직을 useBubbleLocation으로 분리
- 처음 상품을 태그할 때 클릭뿐아니라 드래그로도 태그 가능하도록 수정
- '상품태그 추가' 단계 이후 '상품목록 확인' 단계에서 모달을 그냥 닫을 때 tagStep을 지정해주지않았던 것을 지정하여 문제 해결
- 주석 간소화
<br><br>
<br><br>
- Close #208 
<br><br>
=> ♻️ refactor: 게시글 등록 시 드래그해도 상품 태그 가능하도록 수정

src/pages/AuthenticatedPage/PrivateRoutePage.jsx, src/pages/AuthenticatedPage/PublicRoutePage.jsx
<br>
프로그램 실행시 로그인이 되어있는 상태에서 alert창이 뜨는 현상을 해결했다.
<br><br>
sessionStorage는 창을 닫을때는 삭제되고, 새로고침을 하면 유지되기 때문에 이를 이용하였다.
로그인이 되어있는 상태에서 최초 실행시 sessionStorage값이 없으므로 alert창이 뜨지 않고, sessionStorage값을 true로 설정한다. 이후 새로고침시 true값이 유지되어 잘못된 접근시 alert창이 뜨도록 하였고, 창을 닫으면 sessionStorage값은 삭제된다.
<br><br>
<br><br>
- Close #217 
<br><br>
=> ♻️ refactor: 프로그램 실행시 로그인이 되어있는 상태에서 alert창이 뜨는 현상 해결 

src/components/Follow/FollowButton/FollowButton.jsx, src/components/common/Spinner/Spinner.jsx, src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx, src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx, src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
<br>
팔로우, 언팔로우를 했을 때 전체 페이지 로딩으로 인한 깜빡임 현상을 해결하였다.
<br><br>
- 페이지에 있던 팔로우, 언팔로우 API 요청 로직을 FollowButton 컴포넌트에 분리하였다.
- 팔로우, 언팔로우 요청이 로딩중일 때 약간의 시간이 걸리는 것을 대비하여 텍스트 대신에 Spinner 컴포넌트를 보여주었다. 이에 따른 Spinner의 스타일 또한 수정하였다.
- UserSimpleInfo 컴포넌트에 onClick과 onClickFollow 두 가지의 props가 불필요하게 사용되고 있어 onClick props로 통일하였다.
<br><br>
<br><br>
- Close #230 
<br><br>
=> 🐛 fix: 팔로우, 언팔로우시 깜빡임 현상 해결

src/components/PostUpload/ModalProductItem/ModalProductItemStyle.jsx, src/components/PostUpload/ModalProductList/ModalProductList.jsx, src/components/PostUpload/PostProductTag/PostProductTag.jsx
<br>
판매 상품이 있어도 목록을 받아오지 못하는 문제를 해결하고, 판매상품이 있더라도 추가 등록할 수 있는 버튼을 추가했다.
<br><br>
- 이미지 업로드 시 최적화 작업을 하면서 postImgUpload 컴포넌트에서 실수로 빠졌던 상품목록 정보를 가져오는 함수를 보기 좋게 상품목록을 확인할 수 있는 postProductTag 컴포넌트로 이동시켜 이해하기 쉽도록하여, 판매 상품이 있어도 목록을 받아오지 못하는 문제를 해결했다.
-  판매상품이 있더라도 추가 등록할 수 있는 버튼을 추가했다.
<br><br>
- 판매목록이 있을 시에도 상품등록을 유도하는  버튼을 추가한 것은 좋으나 현재 상품등록 후 다시 게시글 추가로 돌아왔을 경우 이전의 사진 데이터를 저장하지 못해 처음부터 게시글을 작성해야하므로 사용자 측면에서 좋지않을 수 있다. (논의 후 -> v2.0.0 에 추가 예정)
<br><br>
- Close #247 
<br><br>
=> 🐛 fix: 판매 상품 목록을 받아오지 못하는 문제 해결 및 버튼 추가

src/hooks/useScroll.js
<br>
useScroll에서 발생하는 current값을 못찾는 오류를 수정했다.
<br><br>
클린업함수의 실행 타이밍에 따른 문제로 공식문서에서 같은 문제의 예제코드를 발견하여 확인 후 수정했다.
<br><br>
https://toothsome-debt-b2b.notion.site/useScroll-Effect-Cleanup-Timing-f5c5d0f6948a42e7bd24e46c97545832?pvs=4
<br><br>
- Close #254 
<br><br>
=> 🐛 fix: useScroll에서 발생하는 current값을 못찾는 오류 수정

src/components/common/Button/TopButton/TopButton.jsx, src/hooks/useScroll.js, src/layout/BasicLayout.jsx, src/pages/FeedPage/FeedPage.jsx, src/pages/HomePage/HomePage.jsx, src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
<br>
useScroll와 top버튼 사용 위치를 basiclayout에서 해당 기능이 사용되는 페이지로 옮긴다.
<br><br>
- useScroll와 top버튼 사용 위치를 basiclayout에서 해당 기능이 사용되는 홈, 피드, 프로필 페이지로 옮겼다.
- basiclayout을 forwardRef로 감싸서 ref값을 부모인 페이지에 가져왔다.
- 따라서 basiclayout이 사용되는 모든페이지에서 location을 탐색하고 scoll을 감지할 필요가 없어졌고 useScroll과 topButton 코드도 짧아졌다. 
- 게시글 등록 페이지에서도 탑버튼이 보였던 것을 해결할 수 있었다 
<br><br>
<br><br>
- Close #257 
<br><br>
=> ♻️ refactor: useScroll와 top버튼 사용 위치 옮기기

src/hooks/useScroll.js
<br>
debounce로 인해 reference를 찾지못하는 오류를 해결했다.
<br><br>
- 무작위로 게시글 상세페이지로 넘어갔을 때 reference값을 찾지 못하는 오류가 발생하였으나, debounce로 인해 스크롤하고 0.5초 뒤 스크롤 위치값을 저장하므로 스크롤을 하고 0.5초 이내로 useScroll이 없는 페이지로 넘어갈 경우 reference값을 찾지 못하는 것을 발견했다.
- 따라서 값의 유무에 따라 삼항연산자를 사용하여 오류를 해결했다. 
<br><br>
<br><br>
- Close #267 
<br><br>
=> 🐛 fix: reference.current를 찾지못하는 오류 해결
