FRONTENDSCHOOL5/final-14-BangKKuseok

- src/components/common/Button/Button.jsx
- src/components/common/Button/SocialButton.jsx
- src/styles/GlobalStyle.js
- src/styles/theme.js
<br>
사용되는 기본 스타일의 버튼과 소셜 버튼을 공통 UI 컴포넌트로 구현하였다.
<br><br>
- GlobalStyle에서 기본 폰트 사이즈 적용이 되지 않아 `*` 선택자에서 `:root` 선택자로 스타일 적용
- theme에 yellow 색상 추가
- 사이즈와 타입 등에 따라 다양한 기본 버튼 컴포넌트를 사용할 수 있다.
- 소셜 구분에 따라 아이콘 및 스타일이 다른 소셜 버튼 컴포넌트를 사용할 수 있다.
<br><br>
<br><br>
- Close #3 
<br><br>
> 🎨 style: 버튼 공통 UI 컴포넌트 구현

- src/assets/icons/icon-arrow-left.svg
- src/assets/icons/icon-more.svg
- src/assets/icons/icon-search.svg
- src/components/common/Header/Header.jsx
- src/components/common/Header/HeaderStyle.jsx
<br>
페이지별 헤더 컴포넌트를 구현했다.
<br><br>
* 구조분해할당으로 props를 받아와 화면을 구별한다.
* svg 이미지의 색을 ReactComponent로 변경한다.
<br><br>
<br><br>
- Close #11
<br><br>
> 🎨 style: 페이지별 Header UI 컴포넌트 구현 (#11)

- src/components/common/Input/Input.jsx
<br>
회원가입, 로그인, 프로필 등록/수정, 상품등록에서 사용되는 Input 컴포넌트를 구현하였다.
<br><br>
- 사용자가 입력한 정보를 받을 수 있다.
- 비밀번호를 입력할 때 웹 접근성을 위한 눈 아이콘을 사용하였다.
- eyeIcon, eyeOffIcon으로 눈 아이콘을 컴포넌트화 해서 받아오고, 누를때마다 이미지가 변경되도록 했다.
- eyeOffIcon일때 비밀번호 형식이고, eyeIcon일때 텍스트 형식으로 비밀번호가 보이도록 바뀐다.
- 형식에 맞지 않는 입력일때 빨간 밑줄과 함께 경고메시지가  뜨도록 했다.
<br><br>
<br><br>
- Close #10 
<br><br>
> 🎨 style: 공통 Input UI 구현 

- src/assets/icons/icon-arrow-top.svg
- src/components/common/Header/Header.jsx
- src/components/common/Input/RoundedBottomInput copy.jsx
- src/components/common/Input/RoundedBottomInput.jsx
- src/components/common/Input/RoundedBottomInput/RoundedBottomInput.jsx
- src/components/common/Input/RoundedBottomInput/RoundedBottomInputStyle.jsx
- src/components/common/Input/RoundedInput.jsx
- src/components/common/Input/RoundedInput/RoundedInput.jsx
- src/components/common/Input/RoundedInput/RoundedInputStyle.jsx
- src/styles/GlobalStyle.js
<br>
사용되는 라운디드 인풋, 라운디드바텀 인풋 컴포넌트를 구현했다.
<br><br>
- id와 placeholder를 받아와 사용할 수 있는 라운디드 인풋을 구현했다.
- 위를 상속받아 라운디드 바텀인풋을 만들었다.
- 라운디드 인풋을 서치 헤더에 추가했다.
- 필요하지만 설정되어있지 않던 속성을 글로벌스타일에 추가했다.
<br><br>
Search Header안의 RoundedInput
<br/>
RoundedBottomInput
<br><br>
- Close #18 
<br><br>
> 🎨 style: RoundedInput 공통 UI 컴포넌트 구현

- src/components/common/Navbar/Navbar.jsx
- src/components/common/Navbar/NavbarStyle.jsx
<br>
Navbar 공통 UI 컴포넌트를 구현했다.
<br><br>
* Link to로 라우터 이동
* ReactComponent로 svg 아이콘 스타일링
* location.pathname을 props로 받아 조건식을 사용하여 페이지 이동시 색변경
<br><br>
<br><br>
- Close #14
<br><br>
> 🎨 style: Navbar 공통 UI 컴포넌트 구현

- src/components/common/Alert/Alert.jsx
- src/components/common/Confirm/Confirm.jsx
- src/components/common/Confirm/ConfirmStyle.jsx
<br>
상황에 따른 Confirm창 UI 컴포넌트를 구현했다.
<br><br>
* 버튼을 누르면 Confirm창이 뜬다.
* children과 type을 넘겨주어 Confirm창 안에 내용을 상황에 따라 바꾼다.
<br><br>
- 사용법
```js
<Confirm type='delete' setShowConfirm={setShowConfirm}>
<span>상품을 삭제할까요?</span>
</Confirm>
```
<br><br>
- Close #27
<br><br>
> 🎨 style: Confirm창 UI 컴포넌트 구현

- src/components/common/Button/Button/Button.jsx
- src/components/common/Button/Button/ButtonStyle.jsx
- src/components/common/Button/SocialButton/SocialButton.jsx
- src/components/common/Button/SocialButton/SocialButtonStyle.jsx
- src/components/common/Carousel/Carousel.jsx
<br>
Button 컴포넌트 폴더 구조 변경 및 컨벤션에따라 Carousel 코드 수정
<br><br>
- styled-components의 코드양이 많아짐에 따라 컴포넌트 폴더 구조를 아래와 같이 변경
```
Button
└ Button
└ Button.jsx
└ ButtonStyle.jsx
└ SocialButton
└ SocialButton.jsx
└ SocialButtonStyle.jsx
```
- 컨벤션에 따라 Carousel에서 사용되는 함수명 수정
```
컨벤션: handle + 동작 이벤트(click, change, ...) + 이벤트 적용 대상 (button, modal, ...)
```
<br><br>
- Close #31
<br><br>
> ♻️ refactor: Button 컴포넌트 폴더 구조 변경 및 컨벤션에따라 Carousel 코드 수정

- src/components/common/Navbar/NavbarStyle.jsx
<br>
Navbar 공통 UI 컴포넌트 수정
<br><br>
position: fixed를 주고 width: 100%로 했더니 부모 요소의 width값이 정해져 있어도 Navbar의 너비가 뷰포트의 100%가 됐다. 따라서 Navbar의 width를 고정값을 줬다.
<br><br>
페이지 예시
- Home.jsx
```js
export default function HomePage() {
return (
<div className='wrapper'>
<div className='content'>
{/* Contents */}
</div>
<Navbar />
</div>
);
}
```
- Home.css
```css
.wrapper {
width: 390px;
min-height: 100vh;
}
.content {
overflow-y: scroll;
height: calc(100vh - 68px);
-ms-overflow-style: none;
scrollbar-width: none;
}
.content::-webkit-scrollbar {
display: none;
}
```
- 이후에  미디어 쿼리로 width값 조절해야함.
<br><br>
- Close #33
<br><br>
> 🎨 style: Navbar 공통 UI 컴포넌트 수정

- src/components/common/Header/Header.jsx
- src/components/common/Header/HeaderStyle.jsx
<br>
Header UI 컴포넌트를 리팩토링했다.
<br><br>
화면(type)에 따라 추가되는 css 속성을 switch문으로 나누었다.
(예시)
- feed: 하얀 배경 및 스크롤 시 맨 위 고정
```css
case 'feed':
return css`
background-color: ${({ theme }) => theme.colors.white};
position: absolute;
`;
```
- profile: 서브 색 배경 및 스크롤 시 맨 위 고정X
```css
case 'profile':
return css`
background-color: subCoral;
`;
```
<br><br>
-레이아웃 구조: 헤더와 메인을 하나로 묶어 스크롤이 되도록 한다.
```jsx
<LayoutWrapper>
<LayoutMain>
<Header />
<Main />
</LayoutMain>
<Navbar />
</LayoutWrapper>
```
<br><br>
- Close #30
<br><br>
> ♻️ refactor: Header UI 컴포넌트 리팩토링

- src/components/common/Navbar/NavbarStyle.jsx
<br>
Navbar 컴포넌트 반응형을 위한 스타일 수정
<br><br>
- Close #38 
<br><br>
> 🎨 style: Navbar 컴포넌트 반응형 너비 적용

- src/components/common/Gallery/Gallery.jsx
<br>
Gallery 컴포넌트 props 구조를 리팩토링하고 반응형 디자인을 적용한다.
<br><br>
- 사용되지 않는 props 삭제
- 변환된 데이터만 받아 사용할 수 있도록 구조 변경
- 반응형 디자인 적용
<br><br>
- 사용 방식
```jsx
<Gallery data={} />
```
<br><br>
- Close #39 
<br><br>
> ♻️ refactor:  Gallery 컴포넌트 데이터 구조 리팩토링 및 반응형 디자인 적용

- src/components/common/UserSimpleInfo/UserSimpleInfo.jsx
- src/components/common/UserSimpleInfo/UserSimpleStyle.jsx
<br>
UserSimpleInfo 공통 UI 컴포넌트 구현
<br><br>
- props로 유저 profile 데이터를 가져와 화면에 나타냈다.
- props의 type으로 더보기버튼, 팔로우버튼, 공백을 나눴다.
- 팔로우버튼은 토글 기능으로 구현했다.
<br><br>
- type: follow
- type: more
- type: none
<br><br>
- Close #50
<br><br>
> 🎨 style: UserSimpleInfo 공통 UI 컴포넌트 구현

- src/App.js
- src/api/axiosInstance.js
- src/api/profileApi.js
<br>
api 요청을 위한 axios, react-query 초기 설정을 진행했다.
<br><br>
- Header별 axios 인스턴스를 생성했다.
- React Query Provider를 생성했다.
- 테스트를 위해 profileApi를 생성했다.
<br><br>
- 데이터 api 연동 방법
```jsx
// MyProfilePage.jsx
export default function MyProfile() {
// useEffect(() => {
//   (async () => {
//     const res = await getProfile('test333');
//     setData(res.profile);
//   })();
// }, []);
// console.log(data);
// useEffect 처리 대신 useQuery로 데이터를 패칭할 수 있다.
const { data: profileData, isLoading: isProfileLoading } = useQuery('myProfile', () =>
getProfile('test333'),
);
<ProfilePageWrapper>
{!isProfileLoading && <ProfileCard profile={profileData.profile} />}
...
</ProfilePageWrapper>
...
```
<br><br>
- Close #63 
<br><br>
> ⚙️ config: axios, react-query 초기 설정

- src/components/LoginSignUp/Login/Login.jsx
- src/components/LoginSignUp/Login/LoginStyle.jsx
- src/components/LoginSignUp/Main/Main.jsx
- src/components/LoginSignUp/Main/MainStyle.jsx
- src/components/LoginSignUp/SetUserProfile/SetUserProfile.jsx
- src/components/LoginSignUp/SetUserProfile/SetUserProfileStyle.jsx
- src/components/LoginSignUp/SignUp/SignUp.jsx
- src/components/LoginSignUp/SignUp/SignUpStyle.jsx
- src/components/common/Button/SocialButton/SocialButtonStyle.jsx
- src/components/common/Input/Input.jsx
- src/components/common/Input/InputStyle.jsx
- src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/MainPage/MainPage.jsx
- src/pages/Router.jsx
- src/pages/SignupPage/SignupPage.jsx
<br>
메인, 로그인, 회원가입, 프로필 설정 마크업 및 기능을 구현하였다.
<br><br>
1. 메인페이지에서 이메일로 로그인을 클릭하면 로그인으로, 회원가입을 클릭하면 회원가입으로 이동한다.
2. 로그인에 성공하면 홈으로, 회원가입을 누르면 회원가입으로, 메인으로 돌아가기를 누르면 메인으로 이동한다.
3. 회원가입에 성공하면 프로필설정으로, 로그인을 누르면 로그인으로, 메인으로 돌아가기를 누르면 메인으로 이동한다.
4. 프로필설정에 성공하면 홈으로, 이전으로 돌아가기를 누르면 회원가입으로 이동한다.
5. 로그인에서는 이메일과 비밀번호를 모두 입력한 다음 유효성 검사가 일어난다.
6. 회원가입과 프로필설정에서는 입력창에서 포커스를 잃었을때 바로 유효성 검사가 일어난다.
7. 프로필 설정에서 사용자 이름은 2~10자 이내 한글, 영문, 숫자만 가능
8. ID는 영문, 숫자, . , _ 만 가능하고 영어 대문자 사용시 소문자로 변환해서 체크 후 저장한다.
9. 소개는 적지 않아도 유효성 검사가 일어나지 않는다.
<br><br>
<br><br>
- Close #52 
<br><br>
> 🎨 style: 메인, 로그인, 회원가입, 프로필 설정 마크업 및 기능 구현 (#52)

- src/pages/HomePage/HomePage.jsx
<br>
홈페이지 콘솔창에 경고문이 떠 styled component 위치를 수정했다.
<br><br>
컴포넌트 내에 잘못 넣었던 styled component를 전역으로 빼주었다.
<br><br>
<br><br>
- Close #68
<br><br>
> 🐛 fix: 홈페이지 Styled component 위치 수정

- src/components/common/Confirm/Confirm.jsx
- src/components/common/Confirm/ConfirmStyle.jsx
<br>
Confim의 컨펌할 타입과 오브젝트에 따라 사용하기 쉽도록 리팩토링했다
<br><br>
- 컨펌할 타입과 오브젝트에 따라 쓸 수 있도록 했다.
- z-index를 지정하여 레이어가 가장 위로 올 수 있도록 했다.
- 컨벤션에 맞도록 변수명을 수정했다. 
- confirm 버튼을 눌렀을때 실행되는 함수 props를 추가했다
<br><br>
사용예제
```jsx
export default function XXPage() {
const [isShowConfirm, setIsShowConfirm] = useState(false);
const [confirmType, setConfirmType] = useState({ type: 'report', object: 'comment' });
return (
...
{isShowConfirm && (
<Confirm
type={confirmType.type}
object={confirmType.object}
setIsShowConfirm={setIsShowConfirm}
onClick={handleClickConfirm}
/>
)}
);
}
```
<br><br>
- Close #74 
<br><br>
> ♻️ refactor: confirm 리팩토링

- src/components/Profile/PostList/PostList.jsx
- src/components/common/Header/Header.jsx
- src/components/common/Input/RoundedInput/RoundedInput.jsx
- src/components/common/Input/RoundedInput/RoundedInputStyle.jsx
- src/components/common/UserSimpleInfo/Skeleton/Skeleton.jsx
- src/components/common/UserSimpleInfo/Skeleton/SkeletonStyle.jsx
- src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
- src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx
- src/mock/mockData.js
- src/pages/HomePage/HomePage.jsx
- src/pages/SearchPage/SearchPage.jsx
<br>
검색창 마크업 및 기능 구현, Skeleton UI 구현
<br><br>
- Header, UserSimpleInfo, Navbar를 사용하여 검색창 마크업
- Header의 Input에 text를 입력하면 그 text가 포함된 UserInfo 검색
- UserInfo 클릭하면 User의 프로필로 이동
- text와 일치하는 UserInfo가 없으면 Skeleton UI를 보여줌
- Header의 검색 버튼을 누르면 router가 이동하는 것이 아닌 Search 컴포넌트를 보여주는 방식으로 구현
<br><br>
<br><br>
- Close #62
<br><br>
> ✨ feat: 검색창 마크업 및 기능 구현

- src/api/axiosInstance.js
- src/api/imgApi.js
- src/api/postApi.js
- src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
- src/components/PostUpload/PostProductTag/PostProductTag.jsx
- src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
- src/components/common/Navbar/Navbar.jsx
- src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
<br>
게시글 등록페이지에 api를 연동했다.
<br><br>
- 이미지 업로드와 게시글 api함수를 추가하고 기본 url을 외부에서 쓰도록 export했다.
- 이미지 추가 단계에서 넘어갈 때 이미지가 업로드 되도록했다. 
- 게시글 등록 버튼을 누르면 게시글이 등록되도록 했다. 
- 게시글 등록이 완료되면 해당 게시글의 상세페이지로 이동하도록했다.
- 판매하는 상품이 없는 상황에서도 다음단계로 넘어갈 수 있도록 했다.
- 이미지 업로드 시간과 게시글 업로드 시간을 고려하여 컴포넌트 렌더링 조건문을 추가했다.
<br><br>
<br><br>
- Close #77 
<br><br>
> ✨ feat: 게시글 등록 페이지 API 연동하여 게시글 등록 구현

- src/api/postApi.js
- src/api/profileApi.js
- src/components/PostEdit/PostImgEdit/PostImgEdit.jsx
- src/components/PostEdit/PostImgEdit/PostImgEditStyle.jsx
- src/components/PostEdit/PostTextEdit/PostTextEdit.jsx
- src/components/PostEdit/PostTextEdit/PostTextEditStyle.jsx
- src/components/PostUpload/PostImgUpload/PostImgUploadStyle.jsx
- src/pages/HomePage/HomePage.jsx
- src/pages/PostPage/PostEditPage/PostEditPage.jsx
- src/pages/PostPage/PostEditPage/PostEditPageStyle.jsx
- src/pages/PostPage/PostPage/PostPage.jsx
<br>
게시글 상세페이지에 api를 연동하고, 게시글 수정페이지를 마크업하고 기능구현한다.
<br><br>
- 게시글 상세페이지에 api를 연동했다.
- 게시글 수정 페이지를 마크업했다.
- 게시글 수정기능을 api연동과 함께 구현했다.
- 게시글 api와 관련된 함수를 추가했다
-게시글 업로드 내부 태그를 수정해서 시멘틱한 태그를 사용했다
<br><br>
<br><br>
- Close #82 
<br><br>
> ✨ feat: 게시글 상세페이지 API 연동 및 게시글 수정페이지 마크업과 구현

- src/api/postApi.js
- src/assets/icons/icon-spinner.svg
- src/atoms/post.js
- src/components/common/Spinner/Spinner.jsx
- src/pages/PostPage/PostPage/PostPage.jsx
- src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
<br>
게시글 삭제 기능과 신고기능을 구현했다.
<br><br>
- 게시글 상세페이지에서 삭제기능과 신고기능을 api와 연동하여 구현했다.
- 게시글 상세페이지에서 뒤로가기를 했을경우 이전 페이지가 업로드일 경우 전전 페이지로 이동하도록했다.
- 게시글 상세페이지 데이터 로딩을 기다릴때 보이는 Spinner 컴포넌트를 추가했다. 
<br><br>
<br><br>
- Close #86 
<br><br>
> ✨ feat: 게시글 상세페이지에서의 삭제 및 신고 기능 구현

- src/api/commentApi.js
- src/api/postApi.js
- src/components/PostDetail/CommentItem/CommentItem.jsx
- src/components/PostDetail/CommentItem/CommentItemStyle.jsx
- src/components/PostDetail/CommentSection/CommentSection.jsx
- src/components/common/Input/RoundedBottomInput/RoundedBottomInput.jsx
- src/pages/PostPage/PostPage/PostPage.jsx
- src/pages/PostPage/PostPage/PostPageStyle.jsx
<br>
api와 연동하여 댓글을 작성, 삭제, 신고 기능을 구현했다.
<br><br>
- 댓글 섹션을 컴포넌트로 분리하여 작업했다.
- 댓글을 작성하는 기능을 구현하고 댓글이 업로드됐을 때 스크롤을 가장 하단으로 이동하도록 했다.
- 댓글을 삭제하는 기능과 신고하는 기능을 구현했다. 
- id를 비교하여 내 댓글을 경우 삭제 남의 댓글일 경우 신고하도록 하게 했다.
<br><br>
<br><br>
- Close #88 
<br><br>
> ✨ feat: api 연동하여 댓글 작성,삭제,신고 기능 구현

- src/App.js
<br>
react query devtools를 적용했다.
<br><br>
- 왼쪽 하단의 react query 아이콘으로 devtools를 사용할 수 있다.
<br><br>
- Close #97 
<br><br>
> ⚙️ chore: react query devtools 적용 (#97)

- src/pages/404/NotFoundPage.jsx
<br>
404 페이지를 마크업한다.
<br><br>
feed의 팔로잉 목록이 없을 때의 페이지 스타일 컴포넌트를 상속받아서 404 페이지를 마크업했다.
<br><br>
<br><br>
- Close #107 
<br><br>
> 🎨 style: 404페이지 마크업

- src/api/loginApi.js
- src/api/signupApi.js
- src/components/LoginSignUp/Login/Login.jsx
- src/components/LoginSignUp/SignUp/SignUp.jsx
- src/components/common/Input/Input.jsx
- src/components/common/Input/InputStyle.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/SignupPage/SignupPage.jsx
api와 연동하여 로그인과 회원가입 기능을 구현했다.
<br>
api와 연동하여 로그인과 회원가입 기능을 구현했다.
<br><br>
<로그인>
- 이메일과 비밀번호 형식이 맞지 않을 경우 에러메시지가 뜨게 했다.
- 이메일과 비밀번호를 모두 입력해야 버튼이 활성화되도록 구현했다.
- 이메일 또는 비밀번호가 일치하지 않을 경우 에러메시지가 뜨게 했다.
<회원가입>
- 입력창에서 포커스를 잃으면 바로 유효성 검사가 일어나도록 했다.
- 이메일 또는 비밀번 형식이 맞지 않을 경우 에러메시지가 뜨게 했다.
- 이미 가입된 이메일일 경우 에러메시지가 뜨게 했다.
<br><br>
<로그인>
- 이메일과 비밀번호를 모두 입력해야 버튼이 활성화 되도록
-입력 안하고 onFocus되었을때 에러메시지
- 눈 아이콘을 클릭하면 비밀번호가 보이거나 보이지 않게
- 형식이 맞지 않을 경우 에러메시지
- 이메일 또는 비밀번호가 일치하지 않을 경우 에러메시지
<회원가입>
- 이메일 또는 비밀번호를 입력하지 않았을 경우 에러메시지
- 형식이 맞지 않을 경우 에러메시지
- 이미 가입된 이메일일 경우
- 눈 아이콘을 클릭하면 비밀번호가 보이거나 보이지 않게
<br><br>
- Close #66 
<br><br>
> ✨ feat: api 연동하여 로그인, 회원가입 기능 구현 (#66)

- src/api/postApi.js
- src/components/PostDetail/CommentSection/CommentSection.jsx
- src/components/Profile/PostList/PostList.jsx
- src/components/common/Card/PostCard/PostCard.jsx
- src/components/common/Header/HeaderStyle.jsx
- src/pages/PostPage/PostPage/PostPage.jsx
<br>
댓글을 달거나 삭제해도 ui의 commentCount가 즉각적으로 바뀌지 않는 문제를 해결했다. 
<br><br>
-  댓글 수 state를 만들어 즉각적인 데이터 반영했다.
- PostPage에 사용된 불필요한 useState 사용을 줄이고  useQuery의 데이터를 사용했다.
- spinner가 보이는 조건을 수정하여 로딩 시 보이지않는 문제를 해결했다. 
<br><br>
<br><br>
- Close #119 
<br><br>
> 🐛 fix: 댓글 기능 적용시 데이터가 바로 적용되지 않는 문제 해결

- src/api/productApi.js
- src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
- src/components/PostUpload/PostImgUpload/PostImgUploadStyle.jsx
- src/components/Product/ProductForm/ProductForm.jsx
- src/components/Product/ProductForm/ProductFormStyle.jsx
- src/components/Profile/ProductDetailCard/ProductDetailCard.jsx
- src/components/Profile/ProductList/ProductList.jsx
- src/components/common/Input/Input.jsx
- src/constants/validate.js
- src/hooks/useInputs.js
- src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
- src/pages/ProductPage/ProductEditPage/ProductEditPage.jsx
- src/pages/ProductPage/ProductUploadPage/ProductUploadPage.jsx
- src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
<br>
상품 등록 및 수정 기능을 API와 연동하여 구현한다.
<br><br>
- 상품 등록, 수정 페이지에서 사용하기 위해 게시글 등록에서 사용되는 PostImgUpload 컴포넌트를 수정했다.
- 상품을 등록, 수정할 수 있는 페이지를 마크업했다.
- 각 입력값에 대한 validate 체크를 위한 정규식과 에러 메시지를 상수로 선언했다.
- input에 값을 입력하고, onChange, onBlur 시의 동작들을 useInput custom Hooks를 만들어 중복되는 코드를 최소화했다.
- 상품 수정 페이지로 이동하면, 기존 상품의 값이 기본값으로 보여지게 했다.
<br><br>
- 상품을 등록, 수정할 때 이전 데이터가 살짝 보였다가 현재 데이터로 수정되는 현상이 있다.
<br><br>
- Close #91 
<br><br>
> ✨ feat: 상품 등록, 수정 마크업 및 기능 구현

- src/pages/SearchPage/SearchPage.jsx
<br>
검색 결과 7개씩 보여주는 기능 추가
<br><br>
- 검색 목록을 모두 보여주는 것이 아닌 7개씩 보여주도록 더보기 버튼을 추가했다.
- 마지막 결과가 보여졌을 땐 더보기 버튼이 안보이게 했다.
<br><br>
<br><br>
- Close #128
<br><br>
> ✨ feat: 검색 결과 7개씩 보여주는 기능 추가

- src/components/Profile/PostList/PostList.jsx
- src/components/Profile/ProductDetailCard/ProductDetailCard.jsx
- src/components/Profile/ProductList/ProductListStyle.jsx
- src/components/common/Card/PostCard/PostCard.jsx
- src/components/common/Card/PostCard/PostCardStyle.jsx
- src/components/common/Card/ProductCard/ProductCard.jsx
- src/pages/PostPage/PostPage/PostPage.jsx
<br>
다른 서비스 사용자 경우 게시글 및 상품을 예외 처리한다.
<br><br>
게시글에 space값이 없을 경우 post카드에 예외처리하여 마크업을 진행한다.
게시글의 이미지가 1개 초과일 경우 첫번째 이미지만 사용한다.
게시글의 이미지가 없을 경우 게시글이 보이지 않는다.
상품에 keyword값이 없을 경우 product카드에 예외처리하고, 이미지가 에러가 발생할 경우 기본이미지를 불러온다.
- 상품목록이 스크롤가능하도록한다.
<br><br>
<br><br>
- Close #142 
<br><br>
> ♻️ refactor: 다른 서비스 사용자 경우 게시글 및 상품 예외 처리

- src/pages/FeedPage/FeedPage.jsx
<br>
feed 페이지에서 데이터없을때 search로 이동가능하도록 한다 조건을 추가한다.
<br><br>
<br><br>
<br><br>
- Close #145
<br><br>
> 🐛 fix: feed 페이지에서 데이터없을때 search로 이동가능하도록 하기

- src/components/common/Card/PostCard/PostCard.jsx
<br>
게시글 이미지데이터가 잘못들어올 경우 액박대신 기본 이미지가 보이도록 수정했다.
<br><br>
<br><br>
<br><br>
- Close #149 
<br><br>
> 🐛 fix: 게시글 이미지 오류 처리

- src/atoms/post.js
- src/components/PostUpload/ModalProductList/ModalProductList.jsx
- src/components/PostUpload/ModalProductList/ModalProductListStyle.jsx
- src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
<br>
게시글 작성 시 불러오는 상품목록 api 연동하기
<br><br>
목 데이터를 제거하고 게시글 작성 시 불러오는 상품목록 api 연동한다
<br><br>
<br><br>
- Close #152 
<br><br>
> ♻️ refactor: 게시글 작성 시 불러오는 상품목록 api 연동하기

- src/api/followApi.js
- src/components/Profile/ProfileCard/ProfileCard.jsx
- src/components/common/Header/Header.jsx
- src/components/common/Header/HeaderStyle.jsx
- src/components/common/Navbar/NavbarStyle.jsx
- src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
- src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleStyle.jsx
- src/hooks/useObserver.js
- src/pages/FeedPage/FeedPage.jsx
- src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
- src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPageStyle.jsx
- src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
- src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
<br>
팔로워, 언팔로우 기능을 추가했다.
<br><br>
- 프로필 페이지에서 팔로우, 언팔로우 기능이 가능하다.
- 팔로워, 팔로잉 페이지에서 팔로우 상태를 확인할 수 있다.
- 팔로워, 팔로잉 페이지에서 팔로우, 언팔로우 기능이 가능하다.
<br><br>
- 현재 팔로워, 팔로잉 페이지 무한 스크롤 기능 중 다음 페이지가 있어도 한 번의 다음 페이지만 요청되는 오류가 있다.
<br><br>
- Close #126 
<br><br>
> ✨ feat: 팔로워, 언팔로우 기능 추가

- src/components/PostDetail/CommentItem/CommentItem.jsx
- src/components/Profile/PostList/PostList.jsx
- src/components/common/Header/Header.jsx
- src/components/common/Header/HeaderStyle.jsx
- src/pages/PostPage/PostPage/PostPage.jsx
<br>
게시글 상세페이지에서 user클릭시 해당 profile로 이동할 수 있게한다.
<br><br>
- 헤더의 사용자 이름을 클릭하면 해당 게시글의 프로필로 이동한다.
- 댓글의 유저프로필을 클릭하면 해당 유저의 프로필로 이동한다.
- 피드에서 유저프로필을 클릭하면 해당 유저의 프로필로 이동한다.
<br><br>
<br><br>
- Close #157 
<br><br>
> ✨ feat: user클릭시 해당 profile로 이동하기

- src/components/Profile/ProfileCard/ProfileCard.jsx
<br>
유저 프로필 페이지에서 이미지 없을 때 대체텍스트 대신 기본 프로필 이미지로 수정
<br><br>
<br><br>
<br><br>
- Close #{이슈번호}
<br><br>
> ♻️ refactor: 유저 프로필 페이지에서 이미지 없을 때 대체텍스트 대신 기본 프로필 이미지로 수정

- src/components/LoginSignUp/Main/MainStyle.jsx
<br>
메인 페이지 레이아웃을 반응형에 맞춰 수정한다.
<br><br>
<br><br>
<br><br>
- Close #166 
<br><br>
> 🎨 style: 메인페이지 레이아웃 수정

- src/components/LoginSignUp/Login/Login.jsx
- src/components/LoginSignUp/SignUp/SignUp.jsx
- src/components/common/Navbar/Navbar.jsx
- src/components/common/Navbar/NavbarStyle.jsx
- src/pages/AuthenticatedPage/PrivateRoutePage.jsx
- src/pages/AuthenticatedPage/PublicRoutePage.jsx
- src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
- src/pages/Router.jsx
로그인 상태인 PrivateRoutPage와 로그아웃 상태인 PublicRoutePage를 구분하고 Route 경로를 변경하였다.
<br>
<br><br>
- 경고메시지가 뜨고 해당 URL에 접근하지 못하도록 제한
1. 로그인 상태인 PrivateRoutPage에서 PublicRoutePage 라우터로 감싸진 경로로 이동하려고 할 때
2. 로그아웃 상태인 PublicRoutePage에서 PrivateRoutPage 라우터로 감싸진 경로로 이동하려고 할 때
- 기존 /main -> / 으로, 
- 기존 / -> /home 으로 경로 이름을 변경하였다.
<br><br>
<br><br>
- Close #137 
<br><br>
> ✨ feat: url에서 주소를 직접 입력했을 경우와 로그인 상태가 아닐 때 접근 방지

- src/components/Profile/ProfileCard/ProfileCard.jsx
- src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
- src/pages/ChatPage/ChatRoomPage/ChatRoomPageStyle.jsx
- src/pages/Router.jsx
<br>
User 프로필 페이지에서 채팅 버튼 눌렀을 때 chatRoom페이지로 이동하지 않는 오류 수정
<br><br>
- User 프로필 페이지에서 채팅 버튼 눌렀을 때 chatRoom페이지로 이동하기 위해 username 전달
- 채팅내역이 없을 때 메시지 추가
<br><br>
<br><br>
- Close #169
<br><br>
> 🐛 fix: User 프로필 페이지에서 채팅 버튼 눌렀을 때 chatRoom페이지로 이동하지 않는 오류 수정

- src/components/PostUpload/PostProductTag/PostProductTag.jsx
- src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
<br>
게시글 업로드 시 상품 태그 유도 step으로 넘어가지않는 문제를 해결한다.
<br><br>
- 게시글 업로드 시 처음에도 상품 태그 유도 step으로 넘어가지않는 문제를 해결한다.
- 이미지 오류 시 step을 이미지 선택으로 돌아가는 step으로 변경한다.
<br><br>
<br><br>
- Close #174 
<br><br>
> 🐛 fix: 게시글 업로드 시 상품 태그 유도 step으로 넘어가지않는 문제 해결

- src/pages/SignupPage/SignupPage.jsx
<br>
회원가입 후 웰컴페이지가 뜨고 로그인 페이지로 이동하도록 구현하였다.
<br><br>
- setStep("환영합니다") 상태변경을 회원가입이 성공한 후에 이루어지도록 수정하였다.
<br><br>
<br><br>
- Close #171
<br><br>
> 🐛 fix: 회원가입 후 빈화면이 뜨는 오류 해결

- src/components/common/UserSimpleInfo/OtherSimpleInfo/OtherSimpleInfo.jsx
<br>
OtherSimpleInfo는 ChatList에서 쓰이므로 그에 맞게 styled-component 변수명으로 수정하였다.
<br><br>
Wrapper -> ChatSnippet
ChatDate -> ChatListDate
<br><br>
<br><br>
- Close #179 
<br><br>
> 🚚 rename: OtherSimpleInfo의 styled-component 변수명 수정 

- src/components/common/Tabs/SpaceTabs.jsx
<br>
HomePage 탭 버튼 눌렀을 때 크기 달라지는 디자인 수정
<br><br>
<br><br>
<br><br>
- Close #184
<br><br>
> 🎨 style: HomePage 탭 버튼 눌렀을 때 크기 달라지는 디자인 수정

- src/pages/SignupPage/SignupPage.jsx
<br>
이미지를 업로드하지 않고 회원가입을 했을 시, 서버에서 제공되는 기본 이미지가 아닌 우리가 저장한 기본 프로필 이미지를 적용하였다.
<br><br>
이미지의 업로드 여부에 따라 조건부로 이미지를 서버에 전달하였다.
<br><br>
<br><br>
- Close #177 
<br><br>
> 🐛 fix: 회원가입 성공 후 기본 이미지 세팅 오류 해결

- src/mock/mockData.js
<br>
캐러셀 디자인 수정을 위한 목데이터 topLikedPosts 수정
<br><br>
<br><br>
<br><br>
- Close #186
<br><br>
> 🎨 style: 캐러셀 목데이터 디자인 수정

- src/components/common/Carousel/Carousel.jsx
- src/mock/mockData.js
<br>
팔로우한 계정 없을 때 캐러셀 링크 클릭하면 post detail 페이지가 없어 발생하는 오류 를 수정했다.
<br><br>
<br><br>
<br><br>
- Close #188
<br><br>
> 🐛 fix: 팔로우한 계정 없을 때 캐러셀 링크 클릭하면 발생하는 오류 수정

- src/pages/SignupPage/SignupPage.jsx
<br>
id 유효성 검사 시 소문자로 변환하여 api에 전달하였다.
<br><br>
소문자로 변경해주는 toLowerCase 사용
<br><br>
`idMutation.mutate({ user: { accountname: preData.accountname.toLowerCase() } });`
<br><br>
- Close #193 
<br><br>
> 🐛 fix: 프로필 설정에서 이미 가입된 아이디를 대문자로 입력하고 바로 방꾸석 시작하기 버튼을 눌렀을때 가입되는 오류 해결

- src/api/postApi.js
- src/pages/PostPage/PostEditPage/PostEditPage.jsx
<br>
게시글 수정 페이지에 axios함수 변경에 따라 props값 수정한다.
<br><br>
게시글 수정 페이지에 axios함수 변경에 따라 props값 수정하고,
수정된 데이터를 받는 함수도 수정한다
<br><br>
<br><br>
- Close #199 
<br><br>
> 🐛 fix: 게시글 수정 페이지 axios함수 변경에 따른 props값 수정 (#199)

- src/assets/icons/icon-search.svg
- src/components/common/Header/HeaderStyle.jsx
- src/components/common/UserSimpleInfo/UserSimpleInfo/UserSimpleInfo.jsx
- src/pages/HomePage/HomePage.jsx
<br>
HomePage 게시글이 없을 때 '아직 등록된 게시물이 없습니다' 메시지 출력 안되는 오류 수정
<br><br>
- 홈페이지 게시물 없을 때 아직 등록된 게시물이 없습니다 메시지 안보이는 버그 수정
- refetchOnWindowFocus: true 삭제
- 검색에서 key props 오류 해결
- post detail에서 링크에 cursor: pointer 추가
<br><br>
<br><br>
- Close #201
<br><br>
> 🐛 fix: HomePage 게시글이 없을 때 '아직 등록된 게시물이 없습니다' 메시지 출력 안되는 오류 수정

- src/assets/icons/icon-search.svg
<br>
흰 배경일 때 흰 돋보기 모양이 보이지 않아 box-shadow가 들어간 아이콘으로 수정
<br><br>
<br><br>
<br><br>
- Close #195 
<br><br>
> 🎨 style: 검색 아이콘 shadow 수정

- src/components/LoginSignUp/Main/MainStyle.jsx
- src/components/LoginSignUp/SignUp/SignUpStyle.jsx
- src/layout/BasicLayout.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/SignupPage/SignupPage.jsx
- src/pages/SplashPage/SplashStyle.jsx
- src/styles/GlobalStyle.js
<br>
반응형으로 브라우저의 크기가 늘어났을 때 애플리케이션과의 경계를 구분하기 위해 root에 배경색을, 애플리케이션에 box-shadow를 적용한다.
<br><br>
- root에 배경색 적용
- 애플리케이션 레이아웃들에 box-shadow 적용
- Signup 페이지의 SignupHeader 부분에 margin-top을 padding-top으로 변경
<br><br>
- Close #203 
<br><br>
> 🎨 style: 애플리케이션 배경색 및 box-shadow 설정

- README.md
<br>
<br><br>
<br><br>
<br><br>
- Close #{이슈번호}
<br><br>
> 📝 docs: README.md 수정 (#158)

- src/api/postApi.js
- src/constants/pagenation.js
- src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
<br>
프로필 페이지에서 게시글에 무한 스크롤링을 적용했다.
<br><br>
- api 요청시 limit을 상수로 선언했다.
- useInfiniteQuery와 useObserver를 사용하여 무한 스크롤링을 적용했다.
<br><br>
간혹 새로고침 시 무한 스크롤이 적용되지 않는 오류가 발생했다. 확인해보니 잦은 새로고침 시 useObserver가 제대로 호출되지 않을 때가 있어 react-query 리팩토링 시 확인할 필요가 있을 것 같다.
<br><br>
- Close #213
<br><br>
> ✨ feat: 프로필 페이지 게시글 무한 스크롤링 적용

- src/components/Profile/ProductDetailCard/ProductDetailCardStyle.jsx
- src/components/common/BottomSheet/BasicModal.jsx
<br>
상품 상세 모달에 반응형을 적용했다.
<br><br>
- 스크린이 500px 미만일 때는 `flex` 를 사용하여 정렬하고, 500px 이상일 때는 `grid`를 사용하여 사용자가 보기 편한 레이아웃으로 적용했다.
<br><br>
<br><br>
- Close #215 
<br><br>
> 🎨style: 상품 상세 모달 반응형 적용

- package-lock.json
- package.json
- src/components/PostUpload/PostImgUpload/PostImgUpload.jsx
- src/components/PostUpload/PostProductTag/PostProductTag.jsx
- src/components/PostUpload/PostTextWrite/PostTextWrite.jsx
- src/components/Product/ProductForm/ProductForm.jsx
- src/components/common/ProfileImageUpload/ProfileImageUpload.jsx
- src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
<br>
이미지 업로드 시 이미지 용량을 최적화하고 예외처리했다.
<br><br>
- browser-image-compression 라이브러리를 추가한다
- api의 이미지 업로드 용량 제한에 따라 업로드 시 이미지 용량을 최적화한다.
- api에서 사용 불가능한 이미지 확장자를 사용가능한 확장자로 변경하여 업로드한다.
- 상품 이미지, 프로필 이미지 등록 시에도 모두 api에 이미지를 업로드하도록 수정한다.
- 변수명을 수정하여 가독성을 높인다.
<br><br>
<br><br>
- Close #211 
<br><br>
> ♻️ refactor: 이미지 업로드 시 최적화 및 예외처리

- src/components/Profile/ProductList/ProductList.jsx
- src/components/common/Tabs/SpaceTabs.jsx
- src/hooks/useSwipe.js
- src/pages/HomePage/HomePage.jsx
<br>
스와이프 기능을 Custom hook으로 빼고 ProductList에 Swipe 기능 추가
<br><br>
- 기존 홈페이지 swipe 코드를 간소화하여 코드의 길이를 줄였다.
- 스와이프 기능을 Custom hook으로 빼고 ProductList에 Swipe 기능을 추가했다.
<br><br>
<br><br>
- Close #243 
<br><br>
> ♻️ refactor: 스와이프 기능을 Custom hook으로 빼고 ProductList에 Swipe 기능 추가

- src/pages/404/NotFoundPage.jsx
<br>
PC버전에서 배경색을 넣으면서 투명하여 이상했던 404 페이지의 백그라운드를 흰색으로 지정했다.
<br><br>
<br><br>
<br><br>
- Close #245 
<br><br>
> ♻️ refactor: 404 페이지 배경색 지정

- src/atoms/myProfile.js
- src/components/PostDetail/CommentItem/CommentItem.jsx
- src/components/PostDetail/CommentSection/CommentSection.jsx
- src/components/PostUpload/PostProductTag/PostProductTag.jsx
- src/components/Profile/ProfileCard/ProfileCard.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/PostPage/PostPage/PostPage.jsx
- src/pages/ProfilePage/FollowPage/FollowersPage/FollowersPage.jsx
- src/pages/ProfilePage/FollowPage/FollowingsPage/FollowingsPage.jsx
- src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
- src/pages/ProfilePage/ProfilePage/ProfilePage.jsx
<br>
내 프로필 정보를 필요할 때마다 각 페이지에서 api를 요청해서 사용했던 부분을 recoil에서 가져와 사용하게 수정했다.
<br><br>
- 로그인 시 내 프로필 정보를 로컬 스토리지, recoil에 저장
- 내 프로필 정보가 필요할 때마다 api 요청이 아닌 recoil에서 가져와 사용
- 프로필 수정시 recoil hooks인 useRecoilState를 사용하여 recoil에 저장된 정보 변경
<br><br>
로그인 시 데이터를 로컬 스토리지에 저장하게 되면 토큰 값 등 사용자의 정보가 로컬 스토리지에 저장되는데 보안상 괜찮을지
<br><br>
- Close #251 
<br><br>
> ✨ feat: 내 프로필 정보 recoil로 관리하기

- src/components/PostUpload/PostProductTag/PostProductTag.jsx
- src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
<br>
게시글 등록 시 상품 태그없이도 넘어갈 수 있도록 했다.
<br><br>
기존에는 유저가 등록한 상품이 아예 없을때만 상품 태그를 하지않아도 넘어갈 수 있도록 해던 것을 상품태그 없이도 가능하도록 수정했다.
<br><br>
<br><br>
- Close #259 
<br><br>
> ♻️ refactor: 게시글 등록 시 상품 태그없이도 넘어갈 수 있도록 하기

- src/components/common/Button/SocialButton/SocialButtonStyle.jsx
<br>
main의 버튼들이 hover 되었을 시 배경색이 변하도록 수정하였다.
<br><br>
opacity: 0.2
<br><br>
<br><br>
- Close #240 
<br><br>
> 🎨 style: 메인의 소셜버튼 hover시 스타일 지정하기 

- src/api/feedApi.js
- src/api/homeApi.js
- src/constants/pagenation.js
- src/pages/FeedPage/FeedPage.jsx
- src/pages/HomePage/HomePage.jsx
<br>
홈, 피드 페이지 limit값을 상수로 분리한다
<br><br>
- 홈 목록 데이터 저장에서 state 사용을 지양하고 useQuery 중심으로 사용한다
- 홈 페이지와 피드페이지에서 limit값을 상수로 분리한다
<br><br>
<br><br>
- Close #250 
<br><br>
> ♻️ refactor: 홈, 피드 페이지 limit값을 상수로 분리

- src/assets/icons/icon-upload.svg
- src/components/common/Navbar/Navbar.jsx
- src/components/common/Navbar/NavbarStyle.jsx
<br>
Navbar 디자인 수정
<br><br>
- Navbar에 라벨 추가
- icon-upload.svg 수정
<br><br>
- Close #225
<br><br>
> 🎨 style: Navbar 디자인 수정

- public/index.html
- src/App.js
- src/components/LoginSignUp/LoginSignUp/LoginSignUpStyle.jsx
- src/components/LoginSignUp/Main/MainStyle.jsx
- src/components/LoginSignUp/SetUserProfile/SetUserProfileStyle.jsx
- src/components/LoginSignUp/Welcome/WelcomeStyle.jsx
- src/components/common/BottomSheet/BottomSheetStyle.jsx
- src/components/common/Confirm/ConfirmStyle.jsx
- src/components/common/Spinner/Spinner.jsx
- src/layout/BasicLayout.jsx
- src/pages/ChatPage/ChatRoomPage/ChatRoomPageStyle.jsx
- src/pages/FeedPage/FeedPageStyle.jsx
- src/pages/SplashPage/SplashStyle.jsx
- src/styles/GlobalStyle.js
<br>
safari에서 봤을 때 100vh 스크롤이 생기는 것을 변수를 사용하여 해결했다.
<br><br>
[React 모바일 웹 앱 100vh 실제 화면 크기로 맞추기](https://velog.io/@eunddodi/React-%EB%AA%A8%EB%B0%94%EC%9D%BC-%EC%9B%B9-%EC%95%B1-100vh-%EC%8B%A4%EC%A0%9C-%ED%99%94%EB%A9%B4-%ED%81%AC%EA%B8%B0%EB%A1%9C-%EB%A7%9E%EC%B6%94%EA%B8%B0)
<br><br>
- Close #269 
<br><br>
> ♻️ refactor: safari에서 봤을 때 100vh 스크롤 해결

- public/index.html
<br>
meta 태그를 사용해 검색엔진 최적화를 한다.
<br><br>
meta 태그를 사용해 검색엔진 최적화를 한다.
<br><br>
<br><br>
- Close #271 
<br><br>
> ♻️ refactor: meta 태그를 사용한 SEO
